// Auto-generated gallery data
const iconsData = {
    CATEGORY_BY_ICON_NAME: {
    "barcode": "category",
    "calculator": "category",
    "courier": "category",
    "credit-blank": "category",
    "folder-outline": "category",
    "internet": "category",
    "law": "category",
    "person-add": "category",
    "person-check": "category",
    "person-clientcard": "category",
    "person-customer-details-off": "category",
    "person-customer-details": "category",
    "person-group": "category",
    "person-loyality": "category",
    "person-owner": "category",
    "person-profile": "category",
    "person-self-employed": "category",
    "person-seller": "category",
    "person": "category",
    "personnel": "category",
    "restaurant": "category",
    "scissors": "category",
    "service-package": "category",
    "service": "category",
    "shipping": "category",
    "terminal-rent": "category",
    "transport": "category",
    "happy": "emotions",
    "neutral": "emotions",
    "sad": "emotions",
    "very-happy": "emotions",
    "very-sad": "emotions",
    "bell": "header",
    "cart": "header",
    "close": "header",
    "exit": "header",
    "menu": "header",
    "order": "header",
    "profile": "header",
    "request": "header",
    "search": "header",
    "settings": "header",
    "arrow-back": "info",
    "arrow-down": "info",
    "arrow-forward": "info",
    "arrow-up": "info",
    "down-circle-add": "info",
    "down-circle": "info",
    "graph": "info",
    "left-circle": "info",
    "megaphone": "info",
    "right-down": "info",
    "rouble": "info",
    "sale": "info",
    "up-circle-add": "info",
    "up-circle": "info",
    "warehouse": "info",
    "web": "info",
    "arrow-left": "navigation",
    "arrow-northeast": "navigation",
    "arrow-right": "navigation",
    "arrow-southwest": "navigation",
    "chevron-down-rounded": "navigation",
    "chevron-left": "navigation",
    "chevron-right": "navigation",
    "chevron-up-rounded": "navigation",
    "double-arrow-down": "navigation",
    "double-arrow-left": "navigation",
    "double-arrow-right": "navigation",
    "double-arrow-up": "navigation",
    "drop-down": "navigation",
    "drop-up": "navigation",
    "expand-less": "navigation",
    "expand-more": "navigation",
    "fold-horizontal": "navigation",
    "fold": "navigation",
    "low-priority": "navigation",
    "minimize": "navigation",
    "minus-outlined": "navigation",
    "more": "navigation",
    "plus-outlined": "navigation",
    "sorting": "navigation",
    "subdirectory-left": "navigation",
    "subdirectory-right": "navigation",
    "unfold-horizontal": "navigation",
    "unfold-less": "navigation",
    "unfold-more": "navigation",
    "accounting-nav": "side-menu",
    "acquiring": "side-menu",
    "bill-correction": "side-menu",
    "bill": "side-menu",
    "bookshelf": "side-menu",
    "combined": "side-menu",
    "credit": "side-menu",
    "datamatrix": "side-menu",
    "edo": "side-menu",
    "go-market": "side-menu",
    "key": "side-menu",
    "lk": "side-menu",
    "my-apps": "side-menu",
    "payment": "side-menu",
    "purchase": "side-menu",
    "qr": "side-menu",
    "reports": "side-menu",
    "research-nav": "side-menu",
    "reviews": "side-menu",
    "rouble-outlined": "side-menu",
    "sber": "side-menu",
    "services": "side-menu",
    "shop-2": "side-menu",
    "shop": "side-menu",
    "stats": "side-menu",
    "support-add": "side-menu",
    "support": "side-menu",
    "wallet": "side-menu",
    "accounting": "system",
    "alco": "system",
    "alert-circle": "system",
    "alert-triangle": "system",
    "alert": "system",
    "archive": "system",
    "article": "system",
    "attach": "system",
    "block": "system",
    "book": "system",
    "brand": "system",
    "bulb": "system",
    "bundle": "system",
    "business-case": "system",
    "calendar": "system",
    "call-end": "system",
    "call-later": "system",
    "cashback": "system",
    "cast": "system",
    "chart": "system",
    "chat": "system",
    "check-all": "system",
    "check-rounded": "system",
    "check-square-outlined": "system",
    "check": "system",
    "clock-outlined": "system",
    "clock-solid": "system",
    "clock": "system",
    "comment": "system",
    "compare-add": "system",
    "compare-remove": "system",
    "comparsion": "system",
    "copy": "system",
    "crown": "system",
    "decline": "system",
    "delete-outlined": "system",
    "delete-solid": "system",
    "delete": "system",
    "dialog": "system",
    "display-mode": "system",
    "doc": "system",
    "document-copy": "system",
    "document-filled": "system",
    "document": "system",
    "download": "system",
    "drag": "system",
    "edit-rounded": "system",
    "edit": "system",
    "empty-cart": "system",
    "event": "system",
    "external-link": "system",
    "eye-off": "system",
    "eye": "system",
    "feed": "system",
    "file": "system",
    "filter": "system",
    "fire": "system",
    "fiscal": "system",
    "folder-alert": "system",
    "folder-check": "system",
    "folder-few-check": "system",
    "folder-move": "system",
    "folder": "system",
    "gift": "system",
    "go-to-chat": "system",
    "go-to-minichat": "system",
    "goods": "system",
    "graph-square": "system",
    "healing": "system",
    "help-outlined": "system",
    "help-solid": "system",
    "help": "system",
    "history": "system",
    "id": "system",
    "image": "system",
    "import-export": "system",
    "import": "system",
    "incoming-call": "system",
    "info": "system",
    "insurance": "system",
    "insurancelost": "system",
    "lamp": "system",
    "like": "system",
    "linked-circle-outlined": "system",
    "linked-rounded": "system",
    "linked": "system",
    "list": "system",
    "location-arrow": "system",
    "location-pin": "system",
    "location": "system",
    "lock": "system",
    "login": "system",
    "logo-1c": "system",
    "logo-android": "system",
    "logo-apple": "system",
    "logo-chestniy-znak": "system",
    "logo-evotor": "system",
    "logo-facebook": "system",
    "logo-gomarket": "system",
    "logo-instagram": "system",
    "logo-linux": "system",
    "logo-ok": "system",
    "logo-sber": "system",
    "logo-sbp": "system",
    "logo-telegram": "system",
    "logo-twitter": "system",
    "logo-vk": "system",
    "logo-whatsapp": "system",
    "logo-windows": "system",
    "mail": "system",
    "minus-rounded": "system",
    "minus": "system",
    "monitoring": "system",
    "mute-1": "system",
    "mute": "system",
    "new": "system",
    "news": "system",
    "offline": "system",
    "online": "system",
    "open-outside": "system",
    "os-version": "system",
    "outgoing-call": "system",
    "password": "system",
    "paste": "system",
    "pause-circle": "system",
    "pause": "system",
    "phone": "system",
    "pickup-point": "system",
    "pin-outline": "system",
    "pin": "system",
    "play-circle": "system",
    "plus-rounded": "system",
    "plus": "system",
    "point-up": "system",
    "power-on": "system",
    "power": "system",
    "print": "system",
    "printer": "system",
    "promo": "system",
    "refresh": "system",
    "refund": "system",
    "remote": "system",
    "renew": "system",
    "research": "system",
    "route": "system",
    "sale-options": "system",
    "save": "system",
    "scanner": "system",
    "selected": "system",
    "send": "system",
    "share": "system",
    "sim": "system",
    "smartphone": "system",
    "specify": "system",
    "star-border": "system",
    "star-outlined": "system",
    "star-solid": "system",
    "star": "system",
    "support-agent": "system",
    "swap": "system",
    "sync-error": "system",
    "sync-problem": "system",
    "sync": "system",
    "table": "system",
    "terminal-add": "system",
    "terminal": "system",
    "tools": "system",
    "unarchive": "system",
    "unlock": "system",
    "unpin": "system",
    "upload": "system",
    "usb": "system",
    "user-add": "system",
    "user-check": "system",
    "user-group": "system",
    "user": "system",
    "usergroup": "system",
    "video-call": "system",
    "volume-off": "system",
    "warranty-ended": "system",
    "warranty": "system",
    "wifi": "system",
    "work": "system"
},
    COLOR_ICONS_LIST: [
    "404.svg",
    "alert-circle.svg",
    "alert-triangle.svg",
    "application.svg",
    "assortiment.svg",
    "backup.svg",
    "bank.svg",
    "barcode.svg",
    "battery.svg",
    "big-data.svg",
    "biil.svg",
    "bill.svg",
    "blank.svg",
    "card-attention.svg",
    "card.svg",
    "cards.svg",
    "cash.svg",
    "check.svg",
    "clock.svg",
    "cloud.svg",
    "code.svg",
    "comment-approved.svg",
    "comment-declined.svg",
    "comment.svg",
    "data-matrix-znak.svg",
    "data-matrix.svg",
    "document-fail.svg",
    "document-signed.svg",
    "document.svg",
    "evotor-payment.svg",
    "eye-off.svg",
    "gift.svg",
    "gym.svg",
    "highlight.svg",
    "hr.svg",
    "info-circle.svg",
    "link.svg",
    "mail-new.svg",
    "market.svg",
    "money.svg",
    "news.svg",
    "newspaper.svg",
    "not-found.svg",
    "number-1.svg",
    "number-2.svg",
    "number-3.svg",
    "number.svg",
    "numbers.svg",
    "ok.svg",
    "person.svg",
    "phone.svg",
    "piechart.svg",
    "power.svg",
    "production.svg",
    "purse.svg",
    "qr.svg",
    "rating.svg",
    "recommended.svg",
    "rocket.svg",
    "sad.svg",
    "sbp.svg",
    "settings.svg",
    "shelf.svg",
    "shop.svg",
    "sim-activated.svg",
    "sim-cancel.svg",
    "sim-normal.svg",
    "sim-waiting.svg",
    "software-check.svg",
    "software-fail.svg",
    "software-support.svg",
    "software.svg",
    "stop.svg",
    "tap-on-phone.svg",
    "telegram.svg",
    "terminal-fail.svg",
    "terminal-free.svg",
    "terminal-off.svg",
    "terminal-size.svg",
    "terminal-success.svg",
    "terminal.svg",
    "traffic-light-green.svg",
    "traffic-light-red.svg",
    "traffic-light-yellow.svg",
    "usb.svg",
    "version-check.svg",
    "version-fail.svg",
    "version.svg",
    "wait.svg",
    "waiting.svg",
    "warning.svg",
    "wi-fi.svg",
    "wifi.svg"
]
};
